export default {
    API_CALL: "API_CALL",

    PERSON: {
        GET_COLUMNS_REQUEST: "GET_COLUMNS_REQUEST",
        GET_COLUMNS_SUCCESS: "GET_COLUMNS_SUCCESS",
        GET_COLUMNS_FAIL: "GET_COLUMNS_FAIL",

        FIND_BY_COLUMN_REQUEST: "FIND_BY_COLUMN_REQUEST",
        FIND_BY_COLUMN_SUCCESS: "FIND_BY_COLUMN_SUCCESS",
        FIND_BY_COLUMN_FAIL: "GET_COLUMNS_FAIL",
    }
}